### ISSUE TITLE
Metadata Ingestion: 'Advanced -> Add extra pip libraries for an ingestion execution' are not installed in scheduled runs

### ISSUE THREAD

**Issue by igorvoltaic** [datahub-project/datahub#10289]
**Describe the bug**
if you add new metadata ingestion and on [name source step](https://github.com/datahub-project/datahub/blob/20e2cc7eca92cc61b7761adc7793f2137f8c1994/datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx#L127) add: 'Advanced -> Add extra pip libraries for an ingestion execution' they will be installed only in manual runs but **not installed in scheduled runs**

**To Reproduce**
1. Create ingestion source following this guide -> https://datahubproject.io/docs/ui-ingestion/#creating-an-ingestion-source
2. Enable scheduled runs (i.e. every 5 minutes)
3. While creating, on step **4 (Finish up)** add a library to **Advanced** (expand menu) -> **Add extra pip libraries for an ingestion execution**
4. Hit **Save & Run** -> Logs will show that additional pip library is installed
5. Wait for a scheduled run and inspect the log extra pip library is not installed in this case

**Expected behavior**
Add extra pip libraries for an ingestion execution must be installed for both scheduled and manual runs.

**Screenshots**

Manual run:
![photo_2024-04-15 18 15 43](https://github.com/datahub-project/datahub/assets/7091794/1362e3b5-0166-40f0-a381-1ce430045e07)

Scheduled run (same configs):
![photo_2024-04-15 18 15 47](https://github.com/datahub-project/datahub/assets/7091794/13718c61-c336-4e74-898c-fedc166760a9)

**Comment by hsheth2** [comment]
I believe we fixed this in https://github.com/datahub-project/datahub/pull/10195 the other day.

**Comment by igorvoltaic** [comment]
We've bumped our deployment to the latest version and I believe the issue is still there
