### ISSUE TITLE
Token based authentication is currently disabled. Contact your DataHub administrator to enable this feature

### ISSUE THREAD

**Issue by estem** [datahub-project/datahub#13733]
Hi,
I dont know if anyone here has already installed Datahub project using docker-compose. I did so, in a debian machine, but when I tried to log-in i see this error : 

![Image](https://github.com/user-attachments/assets/a66f6cd2-87ac-4d87-a3d4-81e4fa21292e)

here's the docker-compose file :

version: "3.7"

```
services:
  datahub-gms:
    image: acryldata/datahub-gms:head
    container_name: datahub-gms
    environment:
      - EBEAN_DATASOURCE_USERNAME=datahub
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_HOST=datahub-mysql:3306
      - EBEAN_DATASOURCE_URL=jdbc:mysql://datahub-mysql:3306/datahub
      - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
      - GRAPH_SERVICE_IMPL=elasticsearch
      - LOGGING_LEVEL_ROOT=DEBUG
      - ELASTICSEARCH_HOST=datahub-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
      - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
      - KAFKA_BOOTSTRAP_SERVER=datahub-kafka:9092
      - KAFKA_SCHEMAREGISTRY_URL=http://datahub-schema-registry:8081
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
      - ENTITY_SERVICE_ENABLE_RETENTION=true
      - MAE_CONSUMER_ENABLED=true
      - MCE_CONSUMER_ENABLED=true
      - PE_CONSUMER_ENABLED=true
      - UI_INGESTION_ENABLED=true
      - METADATA_SERVICE_AUTH_ENABLED=true
    volumes:
      - ./logs/datahub-gms:/var/log/datahub


    healthcheck:
      test: ["CMD", "curl", "-f", "http://datahub-gms:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - datahub-mysql
      - datahub-kafka
      - datahub-elasticsearch

  datahub-frontend:
    image: acryldata/datahub-frontend-react:head
    container_name: datahub-frontend
    environment:
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - DATAHUB_SECRET=notasecret
      - DATAHUB_TELEMETRY_ENABLED=false
      - KAFKA_BOOTSTRAP_SERVER=datahub-kafka:9092
    depends_on:
      - datahub-gms
    ports:
      - "9002"
    volumes:
      - ./logs/datahub-frontend:/var/log/datahub

  datahub-mysql:
    image: mysql:5.7
    container_name: datahub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: datahub
      MYSQL_DATABASE: datahub
      MYSQL_USER: datahub
      MYSQL_PASSWORD: datahub
    volumes:
      - ./logs/datahub-mysql:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  datahub-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: datahub-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  datahub-kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: datahub-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: datahub-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://datahub-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - datahub-zookeeper

  datahub-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: datahub-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


  datahub-schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    container_name: datahub-schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://datahub-kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: datahub-schema-registry
    depends_on:
      - datahub-kafka

networks:
  default:
    name: datahub-network
```

is my docker-compose is fine please ? is there any thing wrog with it ? why I'm geeting the error message please ?

thanks

**Comment by chatterjee-atanu** [comment]
@estem try setting METADATA_SERVICE_AUTH_ENABLED to true in both _datahub-gms_ and _datahub-frontend_ containers. that should solve this

**Comment by estem** [comment]
@chatterjee-atanu I have just done this, then restart the both containers but I still have the same issue

**Comment by estem** [comment]
@chatterjee-atanu I forgot to mention that the app is behid an proxy nginx, I dont know if it  effects or not..but I must mentioned it.

**Comment by charucjoshi** [comment]
@estem  I tried this and encountered the same error. Here is what fixed it for me:
- TOKEN_SERVICE_ENABLED=true
add this env var in datahub-gms

**Comment by estem** [comment]
@charucjoshi I tried this..still havethe same issue
