### ISSUE TITLE
Task :metadata-ingestion:testQuick FAILED

### ISSUE THREAD

**Issue by zhang-jc** [datahub-project/datahub#5481]
**Describe the bug**

`
=========================== short test summary info ============================
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[folder_no_partition_exclude.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[folder_partition_basic.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[single_file.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[folder_partition_keyval.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[multiple_files.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[file_without_extension.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[folder_no_partition_filename.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[folder_no_partition.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[folder_no_partition_glob.json]
FAILED tests/integration/s3/test_s3.py::test_data_lake_local_ingest[multiple_spec_for_files.json]
==== 10 failed, 562 passed, 37 deselected, 45 warnings in 181.00s (0:03:01) ====

> Task :metadata-ingestion:testQuick FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':metadata-ingestion:testQuick'.
> Process 'command 'bash'' finished with non-zero exit value 1
`

**Desktop (please complete the following information):**
 - OS: Linux frin 5.15.0-41-generic 44~20.04.1-Ubuntu x86_64 GNU/Linux
 - latest code from master branch
 - Python 3.8.10

**Comment by anshbansal** [comment]
Request you to please share the full command and logs that you are seeing. Can you try with re-creating the virtual environment? There was a `boto3` update which might be causing this. Re-creating the virtual environment should solve the problem.

**Comment by zhang-jc** [comment]
@anshbansal 

I have tried re-creating the virtual environment, but the problem still exists.

The full command:


$ python3 -m venv venv

$ source venv/bin/activate

$ ./gradlew build -x test --stacktrace

[build.log](https://github.com/datahub-project/datahub/files/9189089/build.log)

**Comment by anshbansal** [comment]
Just making sure that you have JDK8 installed might help.

This stacktrace should help when someone looks into the error. I was doing a sanity if this was a quick fix. Once team prioritises this someone will reply.

**Comment by zhang-jc** [comment]
JDK version:

$ java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

**Comment by jieni0123** [comment]
Having the same issue, any solution for this?
