### ISSUE TITLE
Ingestion from Databricks' Unity Catalog doesn't work: "no assets were ingested"

### ISSUE THREAD

**Issue by edobrynin-dodo** [datahub-project/datahub#7442]
**Describe the bug**
Ingestion from Databricks' Unity Catalog doesn't work: "no assets were ingested"

**To Reproduce**
1. Run datahub via Docker as it described in docs (datahub docker quickstart)
2. Go to Databricks workspace with Unity Catalog Enabled, create Access Token. Add this token to Datahub as a secret.
3. Check that you have some metadata in your Unity Catalog to ingest (metastores, tables, lineage, etc)
4. In Datahub go to Ingestion -> Create new Source -> Databricks Unity Catalog. Provide the path to your Databricks Workspace and a Datahub's Secret with access token. Push "Test Connection" button, make sure that test was successful.
5. Next -> Next (to skip the scheduler setup, we don't need it now)
6. Set a name for your source, push "Save and Run" then
7. Make sure your run was successful. Open "Details" tab of your run. You can see that the total count of assets ingested is 0. 
Also, there is a text "No assets were ingested" there

**Expected behavior**
All assets from Unity Catalog ingested successfully

**Screenshots**
<img width="795" alt="image" src="https://user-images.githubusercontent.com/98310581/221555984-4b4466a6-3db6-499f-9f5a-9e212712f4f6.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/98310581/221562808-666d3a54-4d9b-4b2d-b2ec-e1e888cce1fe.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/98310581/221562946-766a482b-fdfc-4d6e-97f3-3a09ee6b19e9.png">

<img width="794" alt="image" src="https://user-images.githubusercontent.com/98310581/221851793-fbbc447e-1be3-4b52-8729-23247232bbdc.png">

**Desktop (please complete the following information):**
 - OS: [masOS Ventura 13.2.1]
 - Browser [Google Chrome]
 - Version [109.0.5414.119]

**Additional context**
On the screenshots you can see that my connection from Datahub to Unity Catalog was successful. Also you can see that I have some metadata in my Unity catalog (couple of tables and lineage between them)

**Comment by treff7es** [comment]
@edobrynin-dodo please, can you try out the latest python release (0.10.0.3)? There we fixed a bug which hopefully solves your issue as well. ->

**Comment by edobrynin-dodo** [comment]
UPD: i updated acryl-datahub:

```
python3 -m pip install --upgrade pip wheel setuptools
python3 -m pip install --upgrade acryl-datahub
datahub version

DataHub CLI version: 0.10.0.3
Python version: 3.8.10 (default, Jan 24 2022, 21:22:54) 
[Clang 13.0.0 (clang-1300.0.27.3)]
```

Then I ran datahub:

`datahub docker quickstart`

And repeated steps from the bug's descripition.
Still have the same result unfortunately, 0 assets were ingested

**Comment by treff7es** [comment]
@edobrynin-dodo please, can you share with me your ingestion logs (preferably with debug enabled).
You can attach it here or find me on slack.

**Comment by edobrynin-dodo** [comment]
[exec-urn_li_dataHubExecutionRequest_d288a0a7-ae0b-4d05-8046-d6cdab82d43a.log](https://github.com/datahub-project/datahub/files/10892045/exec-urn_li_dataHubExecutionRequest_d288a0a7-ae0b-4d05-8046-d6cdab82d43a.log)

Hi @treff7es!
Here it is.
I checked the logs and it seems that current docker image uses outdated CLI version:

```
Cli report:
{'cli_version': '0.10.0',
```

**Comment by hsheth2** [comment]
@edobrynin-dodo you can specific a specific version of the datahub CLI through the UI: https://datahubproject.io/docs/ui-ingestion/#advanced-running-with-a-specific-cli-version

**Comment by edobrynin-dodo** [comment]
@hsheth2 Thank you! 
Works fine with CLI 0.10.0.4, so I closed the issue.
Thanks everyone for your help!

**Comment by jjoyce0510** [comment]
Thanks for confirming @edobrynin-dodo !
