### ISSUE TITLE
[bug] Some UI bug with duplication entities in dataset navigation menu  

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#9518]
**Describe the bug**

Every time receive such bug as dublication of hierarchy tree. It looks like this:

![image](https://github.com/datahub-project/datahub/assets/44679014/e501867f-7ff7-43b3-bea2-2e352b9c3b1a)

or this 
![image](https://github.com/datahub-project/datahub/assets/44679014/b6ba03e5-1cf8-435a-b995-6b89630bfb3b)

or this 

![image](https://github.com/datahub-project/datahub/assets/44679014/86f070a1-e59d-4332-9072-59a3ad210f49)
 

**To Reproduce**

**Expected behavior**
So it is difficult to manage. need to delete errors and ingest again. Main things is that there is a need to regenerate dataset urn. urn should be uniq. and there should be no such case sensitive bug when dataset created on different ways. 
 
**Screenshots**
see above 

**Desktop (please complete the following information):**
 - Version [e.g. 0.11]

**Additional context**
I think hierarchy of datasets could be managed by datahub not only by ingestion.  or may be in the ingestion but on more proper and defined way.

**Comment by remisalmon** [comment]
Duplicate of https://github.com/datahub-project/datahub/issues/9276.

**Comment by YuriyGavrilov** [comment]
Still no fix it

**Comment by YuriyGavrilov** [comment]
It is actual

**Comment by Naralas** [comment]
Hi, 
I am facing the exact same issue, any update regarding that ?

**Comment by YuriyGavrilov** [comment]
@github-actions This is not stale. Just nobody wants to fix it :(

**Comment by jason4zhu** [comment]
Hi, just wanna catch up, does this issue fixed in the latest version 0.13.3? Thanks!

**Comment by hhhsir0123** [comment]
We're facing the save issue as well in verison 0.12.x, could anyone help solving? I'll appreciate that.

**Comment by aphonsoar** [comment]
Faced the same problem on version `v0.13.2` 

![image](https://github.com/datahub-project/datahub/assets/56922195/63939dc7-560f-4785-b825-41e8b66286ce)

**Comment by YuriyGavrilov** [comment]
Also have this, with Tableau, oracle, vertica, Postgres ..

**Comment by hsheth2** [comment]
This was largely resolved by https://github.com/datahub-project/datahub/pull/9613 in the 0.13.0 release. This requires that *both DataHub and the datahub CLI* are using versions newer than 0.13.0.

If you previously ingested an entity using an older version of datahub, you will need to rerun ingestion in order to correct this issue. Any entities that are not ingested in that new run may not be corrected - you can check the "last synchronized" timestamp in the UI to validate that things have been ingested.

Finally, in certain cases, this happens due to a desynchronization between mysql and elasticsearch. If the browsePathsV2 aspect in mysql contains container urns, but the browsePathsV2 field in Elastic does not, then using [restore indicies](https://datahubproject.io/docs/api/restli/restore-indices/) will fix that.

**Comment by vejeta** [comment]
The issue is still present in 0.13.0. I can't say yet for 0.14.x.
